// FORM INPUTS LENGTH
export const NICKNAME_MAX_LENGTH = 24;
export const COMMUNITY_TITLE_MAX_LENGTH = 24;
export const COMMUNITY_DESC_MAX_LENGTH = 512;
export const FILE_MAX_SIZE_IN_kB = 200;

// GENERAL
export const ONE_DAY_IN_MS = 86400000;
